### ISSUE TITLE
Add exception handling

### ISSUE THREAD

**Issue by diogosantana** [gitbucket-plugins/gitbucket-announce-plugin#10]
There is no specific exception handling for sending e-mail. This cause a lot of undesirable behavior:

1. No log record are created
2. No e-mail is sended, even if only one rcpt is invalid
3. Server returns HTTP STATUS 500 with the stackstrace string as body, making the browser to show the body as text

You could use [setSendPartial](https://commons.apache.org/proper/commons-email/javadocs/api-release/org/apache/commons/mail/Email.html#setSendPartial(boolean)) to prevent behavior number 2, but it still will needed to handle exception.

It also will be nice to log which e-mails were invalid with [SendFailedException.getInvalidAddresses](http://docs.oracle.com/javaee/6/api/javax/mail/SendFailedException.html#getInvalidAddresses()).

Sorry not to provide a PR, but I don't work with Scala.

**Comment by McFoggy** [comment]
@diogosantana I have introduced checks but unfortunately my local SMTP does not fail when using invalid user/emails adress ; so I am not sure it will solve the issue as expected.
Could you please confirm that the modifications fix your problems in your case.
I have prepared [gitbucket-announce-plugin-1.3-alpha1](https://github.com/McFoggy/gitbucket-announce-plugin/releases/tag/1.3-alpha1) alpha release  for tests : stop gitbucket, download the new jar, replace gitbucket-announce-plugin.jar in your `GITBUCKET\plugins` directory with this new one, and relaunch.
Thanks for your feedback.

**Comment by diogosantana** [comment]
Sure. I'll test it and feed back the result here.
Em 25/02/2016 05:31, "Matthieu Brouillard" <notifications@github.com>
escreveu:

**Comment by diogosantana** [comment]
@McFoggy I do realize that my installation were using Java 7, so I got class version error. I changed to Java 8, but I was still using GitBucket 3.10 (Java 7 compiled) and got the same problem.

Now I will migrate the environment to Java 8 and GitBucket 3.11, but it will take a while because of work requirements. I'll let you know.

**Comment by McFoggy** [comment]
@diogosantana any news? could you try with your SMTP server?

**Comment by diogosantana** [comment]
Not yet. My ops team will upgrade the server environment to match GitBucket requeriments, but it will take some days. My expectation is later this week.

**Comment by diogosantana** [comment]
@McFoggy It worked, the e-mail message were sent to all valid address and a error message was registered to the log. But item 3 is stil occuring.

**Comment by McFoggy** [comment]
@diogosantana I have adapted the code and published a [temporary one on my fork](https://github.com/McFoggy/gitbucket-announce-plugin/releases/download/1.3/gitbucket-announce-plugin-1.3.jar)

Using gmail smtp I do not receive any failure when using non existing emails, so again I need you to test. Thanks for your support and feedback.

**Comment by diogosantana** [comment]
It worked. But when I simulate another kind of Exception (authetication failed) the page show "Announce has been sent.".

I do contribute a PR to your fork, please have a look. With those changes all went well.

**Comment by diogosantana** [comment]
The PR: https://github.com/McFoggy/gitbucket-announce-plugin/pull/1
