### ISSUE TITLE
Separate SMTP settings from the GitBucket "base" settings for the plugin

### ISSUE THREAD

**Issue by laaksokimmo** [gitbucket-plugins/gitbucket-announce-plugin#5]
SMTP settings for the announce should be splitted up:

- SMTP settings (announce plugin)
- SMTP notification settings ("base" GitBucket)

Doing so, we could separate the GIT notifications and it's underlying SMTP usage from any other feature that would require to send email.

We needed to remove the "base" SMTP settings and "send notifications" from the bare GitBucket configuration since it became too verbose with no ability to modity to whom and when the emails are sent out. This, naturally disables the possibility to use announce plugin.

**Comment by McFoggy** [comment]
The issue is not really announce plugin related. I created instead takezoe/gitbucket#893.

The split has first to be done in [gitbucket](takezoe/gitbucket) then we will adapt if needed.

**Comment by McFoggy** [comment]
@laaksokimmo I have pushed PR takezoe/gitbucket#896 to answer the need.
A small change will be required in this plugin to adapt to the proposed new gitbucket settings.

**Comment by laaksokimmo** [comment]
Cool, waiting takezoe to react.

**Comment by laaksokimmo** [comment]
I can verify this is working now, thank you for your actions.

**Comment by McFoggy** [comment]
Ok fine
